/**
 * This function is generated by Webcodesk. Replace this comment with a valuable description.
 * Don't forget to describe outputs and their compatibility with other functions or components.
 */
export const sampleFunction = (
  options,
  { stateByDispatch, history }
) => dispatch => {
  // do something here with options;
  const { text, extraOptions } = options;
  // and pass them forward to the dispatcher
  const dispatchOptions = {
    text,
    extraOptions: {
      extraFlag: extraOptions.extraFlag
    }
  };
  dispatch({ optionsFromInput: dispatchOptions });
};
