import React from 'react';
import { QuickJsonViewTypes } from './QuickJsonView.props';

/**
 * QuickJsonView is generated by Webcodesk. Replace this comment with a valuable description.
 */
class QuickJsonView extends React.Component {

  render() {
    const { data } = this.props;
    return (
      <div>
        <pre>
          <code>
            {JSON.stringify(data, null, 4)}
          </code>
        </pre>
      </div>
    );
  }
}

QuickJsonView.propTypes = QuickJsonViewTypes;

QuickJsonView.defaultProps = {
  data: {},
};

export default QuickJsonView;
